package com.lge.kodroid;
import android.app.*;import android.os.*;import android.app.admin.DevicePolicyManager;import android.content.*;import android.graphics.Color;import android.widget.*;import java.security.*;import java.util.*;import java.nio.charset.StandardCharsets;
public class MainActivity extends Activity{
 android.content.SharedPreferences sp;TextView status,code;KeyPair kp;byte[] channel;String replyTopic,last="";
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("relay",0);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(32,48,32,32);TextView t=new TextView(this);t.setText("Kodroid");t.setTextSize(32);t.setTextColor(Color.BLACK);r.addView(t);TextView i=new TextView(this);i.setText("This device is being protected and managed.");i.setTextSize(18);r.addView(i);code=new TextView(this);code.setText("Preparing secure pairing…");code.setTextSize(28);code.setPadding(0,30,0,30);r.addView(code);status=new TextView(this);status.setText("Connecting to free internet relay…");r.addView(status);setContentView(r);new Thread(()->start()).start();}
 void start(){try{loadKeys();String pc=sp.getString("pairCode","");if(pc.length()==0){pc=String.format(Locale.US,"%06d",new SecureRandom().nextInt(1000000));sp.edit().putString("pairCode",pc).apply();}replyTopic=sp.getString("replyTopic","");if(replyTopic.length()==0){replyTopic=Relay.randomTopic("kd-r-");sp.edit().putString("replyTopic",replyTopic).apply();}final String fpc=pc;runOnUiThread(()->code.setText("Pairing code\n"+fpc));while(true){hello(pc);String resp=Relay.poll(replyTopic,last);for(String line:resp.split("\\n")){String msg=Relay.json(line,"message"),id=Relay.json(line,"id");if(id!=null)last=id;if(msg!=null&&msg.startsWith("PAIR:")){channel=Relay.decryptKey(msg.substring(5),kp.getPrivate());sp.edit().putString("channel",Relay.b64(channel)).apply();runOnUiThread(()->status.setText("Securely paired — waiting for commands"));}}if(channel!=null){String s=sp.getString("lastCmd","");String cm=Relay.poll("kd-cmd-"+topic(channel),s);for(String line:cm.split("\\n")){String msg=Relay.json(line,"message"),id=Relay.json(line,"id");if(id!=null)s=id;if(msg!=null&&msg.length()>0)try{handle(Relay.dec(msg,channel));}catch(Exception ignored){}}sp.edit().putString("lastCmd",s).apply();}Thread.sleep(5000);}}catch(Exception e){runOnUiThread(()->status.setText("Relay error — retrying"));}}
 void hello(String pc)throws Exception{Relay.post(Relay.PAIR,"HELLO|"+pc+"|"+Relay.pub(kp.getPublic())+"|"+replyTopic+"|"+Build.MODEL+"|"+Build.VERSION.RELEASE,"Cache","no");}
 void loadKeys()throws Exception{String pr=sp.getString("priv",""),pu=sp.getString("pub","");if(pr.length()==0){kp=Relay.keys();sp.edit().putString("priv",Relay.b64(kp.getPrivate().getEncoded())).putString("pub",Relay.pub(kp.getPublic())).apply();}else{KeyFactory f=KeyFactory.getInstance("RSA");kp=new KeyPair(f.generatePrivate(new java.security.spec.PKCS8EncodedKeySpec(Relay.unb(pr))),Relay.publicKey(pu));}String ch=sp.getString("channel","");if(ch.length()>0)channel=Relay.unb(ch);}
 String topic(byte[] k){return Relay.b64(k).replace("=","").replace("/","_").replace("+","-");}
 void handle(String j)throws Exception{String a=Relay.json(j,"action"),pkg=Relay.json(j,"packageName");boolean ok=execute(a,pkg);Relay.post("kd-ack-"+topic(channel),Relay.enc("{\"action\":\""+a+"\",\"ok\":"+ok+"}",channel),"Cache","no");runOnUiThread(()->status.setText(ok?"Command completed: "+a:"Command rejected: "+a));}
 boolean execute(String a,String pkg){try{DevicePolicyManager d=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);ComponentName admin=new ComponentName(this,KodroidAdminReceiver.class);if(!d.isAdminActive(admin))return false;if("LOCK".equals(a)){d.lockNow();return true;}if("HIDE".equals(a))return d.setApplicationHidden(admin,pkg,true);if("UNHIDE".equals(a))return d.setApplicationHidden(admin,pkg,false);if("BLOCK_UNINSTALL".equals(a)){d.setUninstallBlocked(admin,pkg,true);return true;}if("UNBLOCK_UNINSTALL".equals(a)){d.setUninstallBlocked(admin,pkg,false);return true;}if("SET_CAMERA_DISABLED".equals(a)){d.setCameraDisabled(admin,true);return true;}if("SET_CAMERA_ENABLED".equals(a)){d.setCameraDisabled(admin,false);return true;}if("SET_SCREEN_CAPTURE_DISABLED".equals(a)){d.setScreenCaptureDisabled(admin,true);return true;}if("SET_SCREEN_CAPTURE_ENABLED".equals(a)){d.setScreenCaptureDisabled(admin,false);return true;}if("CLEAR_APP_STORAGE".equals(a))return d.clearApplicationUserData(admin,pkg,null);if("SUSPEND".equals(a)&&Build.VERSION.SDK_INT>=24)return d.setPackagesSuspended(admin,new String[]{pkg},true,null,null)==null;if("UNSUSPEND".equals(a)&&Build.VERSION.SDK_INT>=24)return d.setPackagesSuspended(admin,new String[]{pkg},false,null,null)==null;return false;}catch(Exception e){return false;}}
}