// Modern management UI
package com.lge.kodroid;
import android.app.*;import android.view.*;import android.app.admin.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.widget.*;import java.security.*;import java.util.*;import java.util.concurrent.Executor;
public class MainActivity extends Activity{
 SharedPreferences sp;TextView status,code,admin,apps;KeyPair kp;byte[]ch;String reply,last="";int blue=Color.rgb(38,99,235),dark=Color.rgb(20,28,45);
 public void onCreate(Bundle b){super.onCreate(b);ui();new Thread(this::loop).start();}
 TextView t(String s,float z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(dark);v.setPadding(0,5,0,5);return v;}
 GradientDrawable card(){GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setCornerRadius(28);return g;}
 LinearLayout sec(String s){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(24,18,24,18);l.setBackground(card());TextView h=t(s,19);h.setTypeface(null,1);l.addView(h);return l;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setTextSize(14);x.setAllCaps(false);x.setTextColor(Color.WHITE);GradientDrawable g=new GradientDrawable();g.setColor(blue);g.setCornerRadius(22);x.setBackground(g);return x;}
 View gap(){Space s=new Space(this);s.setMinimumHeight(12);return s;}
 void ui(){ScrollView sc=new ScrollView(this);sc.setBackgroundColor(Color.rgb(245,247,251));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(22,28,22,28);sc.addView(r);TextView h=t("KODROID",30);h.setTypeface(null,1);r.addView(h);r.addView(t("Secure device management",15));LinearLayout c=sec("Connection");r.addView(gap());r.addView(c);code=t("Pairing code: preparing…",22);c.addView(code);status=t("Starting secure relay…",15);c.addView(status);c.addView(t("Encrypted internet relay • OwnDroid-compatible policy engine",13));LinearLayout p=sec("Device protection");r.addView(gap());r.addView(p);admin=t("",16);p.addView(admin);Button a=b("Activate device administrator");a.setOnClickListener(v->activate());p.addView(a);p.addView(t("Model: "+Build.MODEL+"\nAndroid "+Build.VERSION.RELEASE+" (API "+Build.VERSION.SDK_INT+")",14));LinearLayout i=sec("App inventory");r.addView(gap());r.addView(i);apps=t("No inventory loaded.",14);i.addView(apps);Button refresh=b("Show installed apps");refresh.setOnClickListener(v->inventory());i.addView(refresh);r.addView(gap());r.addView(t("Kodroid runs the management agent; KDAdmin is the remote control center.",13));setContentView(sc);refreshAdmin();}
 void refreshAdmin(){DevicePolicyManager d=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);admin.setText(d.isAdminActive(new ComponentName(this,KodroidAdminReceiver.class))?"✓ Device administrator active":"⚠ Device administrator required");}
 void activate(){ComponentName c=new ComponentName(this,KodroidAdminReceiver.class);Intent i=new Intent(DevicePolicyManager.ACTION_ADD_DEVICE_ADMIN);i.putExtra(DevicePolicyManager.EXTRA_DEVICE_ADMIN,c);i.putExtra(DevicePolicyManager.EXTRA_ADD_EXPLANATION,"Allow Kodroid to enforce the management policies selected in KDAdmin.");startActivityForResult(i,7);}
 protected void onResume(){super.onResume();if(admin!=null)refreshAdmin();}
 void inventory(){try{StringBuilder s=new StringBuilder();List<android.content.pm.ApplicationInfo>a=getPackageManager().getInstalledApplications(0);for(int i=0;i<a.size();i++){if(i==30){s.append("…");break;}s.append(a.get(i).loadLabel(getPackageManager())).append("\n").append(a.get(i).packageName).append("\n\n");}apps.setText(s.toString());}catch(Exception e){apps.setText("Inventory unavailable.");}}
 void loop(){try{keys();String pc=sp.getString("pairCode","");if(pc.isEmpty()){pc=String.format(Locale.US,"%06d",new SecureRandom().nextInt(1000000));sp.edit().putString("pairCode",pc).apply();}reply=sp.getString("replyTopic","");if(reply.isEmpty()){reply=Relay.randomTopic("kd-r-");sp.edit().putString("replyTopic",reply).apply();}final String f=pc;runOnUiThread(()->code.setText("Pairing code\n"+f));while(true){Relay.post(Relay.PAIR,"HELLO|"+pc+"|"+Relay.pub(kp.getPublic())+"|"+reply+"|"+Build.MODEL+"|"+Build.VERSION.RELEASE);String z=Relay.poll(reply,last);for(String x:z.split("\\n")){String m=Relay.json(x,"message"),id=Relay.json(x,"id");if(id!=null)last=id;if(m!=null&&m.startsWith("PAIR:")){ch=Relay.decryptKey(m.substring(5),kp.getPrivate());sp.edit().putString("channel",Relay.b64(ch)).apply();runOnUiThread(()->status.setText("✓ Securely paired — listening for commands"));}}if(ch!=null){String s=sp.getString("lastCmd","");String z2=Relay.poll("kd-cmd-"+topic(ch),s);for(String x:z2.split("\\n")){String m=Relay.json(x,"message"),id=Relay.json(x,"id");if(id!=null)s=id;if(m!=null&&!m.isEmpty())try{handle(Relay.dec(m,ch));}catch(Exception e){}}sp.edit().putString("lastCmd",s).apply();}Thread.sleep(5000);}}catch(Exception e){runOnUiThread(()->status.setText("Relay error — retrying"));}}
 void keys()throws Exception{String pr=sp.getString("priv",""),pu=sp.getString("pub","");if(pr.isEmpty()){kp=Relay.keys();sp.edit().putString("priv",Relay.b64(kp.getPrivate().getEncoded())).putString("pub",Relay.pub(kp.getPublic())).apply();}else{KeyFactory f=KeyFactory.getInstance("RSA");kp=new KeyPair(Relay.publicKey(pu),f.generatePrivate(new java.security.spec.PKCS8EncodedKeySpec(Relay.unb(pr))));}String x=sp.getString("channel","");if(!x.isEmpty())ch=Relay.unb(x);}
 String topic(byte[]k){return Relay.b64(k).replace("=","").replace("/","_").replace("+","-");}
 void handle(String j)throws Exception{String a=Relay.json(j,"action"),pkg=Relay.json(j,"packageName");boolean ok=execute(a,pkg);String extra=a.equals("LIST_APPS")?",\"apps\":"+appJson():"";Relay.post("kd-ack-"+topic(ch),Relay.enc("{\"action\":\""+a+"\",\"ok\":"+ok+extra+"}",ch));runOnUiThread(()->status.setText((ok?"✓ ":"⚠ ")+a));}
 String appJson(){StringBuilder s=new StringBuilder("[");try{List<android.content.pm.ApplicationInfo>a=getPackageManager().getInstalledApplications(0);for(int i=0;i<a.size();i++){if(i>0)s.append(",");s.append("\"").append(a.get(i).packageName).append("\"");}}catch(Exception e){}return s.append("]").toString();}
 boolean execute(String a,String p){try{DevicePolicyManager d=(DevicePolicyManager)getSystemService(DEVICE_POLICY_SERVICE);ComponentName c=new ComponentName(this,KodroidAdminReceiver.class);if(a.equals("PING")||a.equals("LIST_APPS"))return d.isAdminActive(c);if(!d.isAdminActive(c))return false;if(a.equals("LOCK")){d.lockNow();return true;}if(a.equals("HIDE"))return d.setApplicationHidden(c,p,true);if(a.equals("UNHIDE"))return d.setApplicationHidden(c,p,false);if(a.equals("BLOCK_UNINSTALL")){d.setUninstallBlocked(c,p,true);return true;}if(a.equals("UNBLOCK_UNINSTALL")){d.setUninstallBlocked(c,p,false);return true;}if(a.equals("SET_CAMERA_DISABLED")){d.setCameraDisabled(c,true);return true;}if(a.equals("SET_CAMERA_ENABLED")){d.setCameraDisabled(c,false);return true;}if(a.equals("SET_SCREEN_CAPTURE_DISABLED")){d.setScreenCaptureDisabled(c,true);return true;}if(a.equals("SET_SCREEN_CAPTURE_ENABLED")){d.setScreenCaptureDisabled(c,false);return true;}if(a.equals("CLEAR_APP_STORAGE")&&Build.VERSION.SDK_INT>=26){Executor e=Runnable::run;d.clearApplicationUserData(c,p,e,(x,ok)->{});return true;}if(a.equals("SUSPEND")&&Build.VERSION.SDK_INT>=24)return d.setPackagesSuspended(c,new String[]{p},true)==null;if(a.equals("UNSUSPEND")&&Build.VERSION.SDK_INT>=24)return d.setPackagesSuspended(c,new String[]{p},false)==null;return false;}catch(Exception e){return false;}}
}